# Generated by Django 4.1.1 on 2022-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False)),
                ('name_player', models.CharField(max_length=50)),
                ('age_player', models.IntegerField()),
                ('team_player', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id_stadium', models.AutoField(primary_key=True, serialize=False)),
                ('name_stadium', models.CharField(max_length=50)),
                ('location_stadium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False)),
                ('name_team', models.CharField(max_length=50)),
                ('city_team', models.CharField(max_length=50)),
            ],
        ),
    ]
