# Generated by Django 4.1.1 on 2022-09-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=100)),
                ('stadium_location', models.CharField(max_length=100)),
                ('stadium_capacity', models.IntegerField()),
                ('stadium_image', models.ImageField(upload_to='stadiums')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(upload_to='teams')),
                ('team_stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_image', models.ImageField(upload_to='players')),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
        ),
    ]
